<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Verizon smb test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0c0065e0-4a1e-46a6-9321-51ebc62806f2</testSuiteGuid>
   <testCaseLink>
      <guid>f16a4725-660a-408b-aaba-2172c24d0888</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verizon smb happy path</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c3b00-2ae8-4131-8ce4-ad6d2fc53310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33857b1f-754e-4cde-a782-8f5637e41a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>433dd5d8-51dd-47a5-ba56-0fb2d2b92fb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verizon smb happy path</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c3b00-2ae8-4131-8ce4-ad6d2fc53310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33857b1f-754e-4cde-a782-8f5637e41a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36625b29-32cd-40f0-8233-bc3f12401900</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verizon smb happy path</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c3b00-2ae8-4131-8ce4-ad6d2fc53310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33857b1f-754e-4cde-a782-8f5637e41a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac8ae2f3-9eba-4077-8e5e-9faf120ddcb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verizon smb happy path</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c3b00-2ae8-4131-8ce4-ad6d2fc53310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33857b1f-754e-4cde-a782-8f5637e41a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>632892bc-08cf-4152-8d18-d46af567b067</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verizon smb happy path</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c3b00-2ae8-4131-8ce4-ad6d2fc53310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33857b1f-754e-4cde-a782-8f5637e41a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf1bd633-4e40-41d4-a21d-6c0d3fa253c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verizon smb happy path</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c3b00-2ae8-4131-8ce4-ad6d2fc53310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33857b1f-754e-4cde-a782-8f5637e41a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76257d32-a99e-4de6-adab-68fa84b84db8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verizon smb happy path</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c3b00-2ae8-4131-8ce4-ad6d2fc53310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33857b1f-754e-4cde-a782-8f5637e41a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be394796-818c-4be2-89ee-4de1e4b417ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verizon smb happy path</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e1c3b00-2ae8-4131-8ce4-ad6d2fc53310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33857b1f-754e-4cde-a782-8f5637e41a62</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
